name: Aplicação Django

on:
  push:
    branches: [ "6" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Instalar Dependências
        run: |
          python3 -m pip install --upgrade pip
                   pip install pipenv
                   pipenv sync -d
                   pipenv install --deploy --dev
      - name: Rodar Testes Automáticos
        run: |
          pipenv run pytest webdev
