name: Aplicação Django

on:
  push:
    branches: [ "2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install Dependências
      run: |
        pip install pipenv
        sync pipenv --dev
    - name: Rodar Testes Automáticos
      run: |
        python run pytest webdev
