name: Aplicação Django

on:
  push:
    branches: [ "2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Instalar Dependências
        run: |
          pip install pipenv
          sync pipenv --dev
      - name: Rodar Testes Automáticos
        run: |
          python run pytest webdev
